- hosts: server
  tasks:
     - name: rubah content file apabila CentOS
       copy:
          content: "saya adalah server dengan OS CentOS dengan versi 7"
          dest: /etc/motd
       when:
          - ansible_distribution == "CentOS"
          - ansible_distribution_major_version == "7"
